name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc

    - name: Build project
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Upload to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/x86_64-pc-windows-msvc/release/node_install.exe
        asset_name: node_install.exe
        asset_content_type: application/octet-stream
